<?php

static $fid = 1;

if (!function_exists('fthumbnail')) {
  function fthumbnail(array $a)
  {
    if (empty($a['id']))
      $src = 'themes/admin/img/blank.gif';
    else
      $src = strval(new url('?q=attachment.rpc&fid='.
        $a['id'] .',48,48,c&rev='.  $a['rid']));

    $img = mcms::html('img', array(
      'src' => $src,
      'width' => 48,
      'height' => 48,
      'alt' => 'thumbnail',
      ));

    if (!empty($a['id']))
      $img = l('?q=attachment.rpc&fid='. $a['id'], $img);
    else
      $img = l('#', $img);

    return $img;
  }
}

?><table class='files'>
  <tr>
    <th class='fieldname' colspan='2'><?php print $c->label; ?></th>
  </tr>
  <tr class='file' id='fid<?php print $fid++; ?>'>
    <td class='preview'>
      <?php print fthumbnail($d); ?>
      <input type='hidden' class='id'
        name='<?php print mcms_plain($c->value); ?>[id]'
        value='<?php print $d['id']; ?>'
        />
    </td>
    <td class='properties'>
      <div class='tab tab1'>
        <label class='filename pad'>
          <span>Название</span>
          <input class='name'
            readonly='readonly' type='text'
            name='<?php print mcms_plain($c->value); ?>[name]'
            value='<?php  if (!empty($d['filename']))
             	      print mcms_plain($d['filename']); ?>' />
        </label>
        <label class='filetype pad'>
          <span>Тип</span>
          <input class='type'
            readonly='readonly' type='text'
            name='<?php print mcms_plain($c->value); ?>[type]'
            value='<?php print mcms_plain($d['filetype']); ?>'
            class='filetype' />
        </label>
        Добавлен: <span class='dateadded'><?php print $d['created']; ?></span>,
        обновлён: <span class='dateupdated'><?php print $d['updated']; ?></span>
      </div>
      <div class='tab tab2'>
        <label class='filename pad'>
          <input type='file'
            name='<?php print mcms_plain($c->value); ?>' />
        </label>
        Максимальный размер загружаемого файла:
        <?php print ini_get('upload_max_filesize'); ?>.
        Можно также <a href='#pick' class='pickerlite'>выбрать из архива</a>
      </div>
      <div class='tab tab3'>
        <p>
          <label>
            <input type='checkbox'
              name='<?php print mcms_plain($c->value); ?>[deleted]'
              value='1' />
            Удалить
          </label>
        </p>
      </div>
      <div class='filetabs'>
        <u class='tab1'>
          <span class='active'>Свойства</span>
        </u>
        <u class='tab2'>
          <span class='passive'>Заменить</span>
        </u>
        <u class='tab3'>
          <span class='passive'>Удалить</span>
        </u>
      </div>
    </td>
  </tr>
</table>
