<label><span><?php print empty($c->label) ? 'Дополнительный файл' : $c->label; ?>:</span></label>
<div class='attachment-control'>
<div class='preview'>
<span style='display:none'><?php print $d['id']; ?></span>
</div>
<input type='file' name='<?php print $c->value; ?>' />
<?php if (!empty($d['id'])): ?>
<label><input type="checkbox" name="<?php print $c->value; ?>_unlink" value="1" />Удалить файл</label>
<?php endif; ?>
<div class='sep'></div>
</div>
