<!-- default doc widget template --><?php

if (!empty($document)) {
  $data = array(
    'document' => $document,
    'tags' => $tags,
    'schema' => Schema::load($document['class']),
    );

  if (!empty($neighbors))
    $data['neighbors'] = $neighbors;

  $code = template::render($theme, 'type', $document['class'], $data);

  if (!empty($code))
    print html::em('div', array(
      'class' => 'node node-'. $document['class'],
      ), $code);
}
