<!-- default doc widget template --><?php

if (!empty($document)) {
  $data = array(
    'document' => $document,
    'tags' => $tags,
    'schema' => Node::create($document['class'])->schema(),
    );

  if (!empty($neighbors))
    $data['neighbors'] = $neighbors;

  $code = bebop_render_object('type', $document['class'], $theme, $data);

  if (!empty($code))
    print mcms::html('div', array(
      'class' => 'node node-'. $document['class'],
      ), $code);
}
