<?php

if (empty($content) and ($mode != 'report')) {
  print '<h2>Корзина пуста</h2>';
  print '<p>Для добавления товаров в корзину воспользуйтесь ссылками "Добавить в корзину" на страницах с описаниями товаров.</p>';
  print '<p>Список предлагаемых нами товаров доступен в разделе <a href="catalog">Каталог</a>.</p>';
}
else if (($mode == 'details') or ($mode == 'simple'))
{
  print "<form method='post' action=\"". l('cart.rpc')."\" id='cart-form' enctype='multipart/form-data'>";
  print "<input type='hidden' name='widgetname' value='{$widgetname}'>";
  print '<table class="basket_list">';
  print '<thead>';
  print '<tr>';
  print '<th>Наименование</th>';
  print '<th>Цена</th>';
  print '<th>Количество</th>';
  print '<th>Сумма</th>';

  if ($mode == 'details') 
    print '<th>Удалить</th>';

  print '</tr>';
  print '</thead>';

  print '<tbody>';

  foreach ($content as $item) {
    print '<tr>';
    print "<td><a href='#'>{$item['name']}</a></td>";
    print "<td>{$item['price']}</td>";
    print '<td>';

    if ($mode == 'simple')
      print $item['qty'];
    else if ($mode == 'details') 
      print "<input type='text'  name='item[{$item['id']}][qty]' value='{$item['qty']}'/>";

    print '</td>';

    print "<td>{$item['sum']}</td>";

    if ($mode == 'details') 
      print "<td><input type = 'checkbox'  name = 'item[{$item['id']}][delete]' value='1'/></td>";

    print '</tr>';
  }

  print '</tbody>';
  print '</table>';

  print "<b>Общая стоимость заказа:</b> {$sum}<br><br>";
  print '<div>';
  print '<a href='.l("{$widgetname}?{$widgetname}.mode=details"). '>Редактировать заказ</a><br>';
  print '<input type="submit" name="order" value="Оформить заказ" />';
	  
  if ($mode == 'details')
    print '<input type="submit" name="recalc" value="Пересчитать заказ" />';

  print '</div>';
  print '</form>';
}
else if ($mode == 'report')
{
  $total = 0;

  print  "<table>";
  print  "<tr><th>Код</th><th>Название</th><th>Количество</th><th>Цена</th><th>Сумма</th></tr>";

  foreach (CartWidget::getCartContent($items) as $row) {
    print  "<tr>";
    print  "<td>{$row['id']}</td>";
    print  "<td>". mcms_plain($row['name']) ."</td>";
    print  "<td>{$row['qty']}</td>";
    print  "<td style='text-align: right'>{$row['price']}</td>";
    print  "<td style='text-align: right'>{$row['sum']}</td>";
    print  "</tr>";

    $total += $row['sum'];
  }

  print  "<tr><td>&nbsp;</td><td colspan='3'><strong>Итого:</strong></td><td style='text-align: right'><strong>". number_format($total, 2) ."</strong></td></tr>";

  print  "</table>";
}