<?php

mcms::extras('themes/admin/css/bebop.css', false);
mcms::extras('themes/admin/css/style.css', false);
mcms::extras('themes/admin/css/colors-green.css', false);

mcms::extras('themes/all/jquery/jquery.js');
mcms::extras('themes/all/jquery/ui/ui.core.js');
mcms::extras('themes/all/jquery/ui/ui.sortable.js');
mcms::extras('themes/all/jquery/plugins/jquery.suggest.js');
mcms::extras('themes/all/jquery/plugins/jquery.suggest.css');
mcms::extras('themes/all/jquery/plugins/jquery.ifixpng.js');
mcms::extras('themes/all/jquery/plugins/jquery.mcms.tabber.js');
mcms::extras('themes/all/jquery/plugins/jquery.dimensions.js');
mcms::extras('themes/all/jquery/plugins/jquery.bgiframe.js');
mcms::extras('themes/admin/js/bebop.js');

mcms::extras('themes/admin/js/installer.js', false);

?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <base href='<?php print $base; ?>' />
    <?php if (!empty($title)) print html::em('title', $title); ?>
    <?php print mcms::extras(); ?>

    <link rel='shortcut icon' href='themes/all/img/lock.png' type='image/png' />
  </head>
  <body>
    <div id="preloaded_images"></div>

    <div id='all'>
      <div id="top_toolbar">
        <div class="greeting">Здравствуйте, <strong>будущий администратор</strong></div>
        <div class="right">
          <a href="http://code.google.com/p/molinos-cms/issues/list" class="tip">Сообщить о проблеме</a>
        </div>
      </div>

      <div id="content_wrapper">
        <div id='center'>
          <?php if ('error' == $mode): ?>
          <h2>Ошибка</h2>
          <p><?php print $message; ?></p>
          <?php else: ?>
          <h2><?php if (!empty($title)) print $title; ?></h2>
          <?php if (!empty($form)) print $form; ?>
          <?php endif; ?>
        </div>

        <div id="left_sidebar">
          <div class="menu_block">
            <h4>Ссылки:</h4>
            <ul>
              <li><a href="http://code.google.com/p/molinos-cms/">Сайт Molinos CMS</a></li>
              <li><a href="http://code.google.com/p/molinos-cms/">Документация</a></li>
            </ul>
          </div>
        </div>

      </div>
    </div>

    <div id="footer">
      <div class="signature">
        <hr/><?php print mcms::getSignature(null, true); ?>
      </div>
    </div>
  </body>
</html>
