<?php if (!empty($title)) print html::em('h2', $title); ?>
<form action='<?php print $base;
  ?>?q=subscription.rpc&action=subscribe&destination=<?php
  print urlencode($_SERVER['REQUEST_URI']);
  ?>' method='post' enctype='multipart/form-data'>
<input type='text' name='email' value='<?php
  print empty($email) ? null : $email; ?>' />
<input type='submit' value='Подписаться' />
<?php foreach ($enabled as $id) {
  print html::em('input', array(
    'type' => 'hidden',
    'name' => 'sections[]',
    'value' => $id,
    ));
  } ?>

</form>
