<?php if ('gas' == $mode): ?>
<?php if ($onlyform): ?>
<form method="get" action="<?php print $resultpage; ?>">
<input class="formText" type="text" name="<?php print $instance; ?>.query" />
<input class="formSubmit" type="submit" value="Найти" />
</form>
<?php else: ?>
<script src="http://www.google.com/jsapi?key=<?php print $apikey; ?>" type="text/javascript"></script>
<script language="Javascript" type="text/javascript">
//<![CDATA[

google.load("search", "1");

function OnLoad() {
  var dc = new google.search.WebSearch();
  var gres = document.getElementById('<?php print $root; ?>');
  var gctl = document.getElementById('<?php print $formctl; ?>');

  if (gres == null)
    alert('Google Search disabled: element #<?php print $root; ?> not found.');
  else if (gctl == null)
    alert('Google Search disabled: element #<?php print $formctl; ?> not found.');
  else {
    dc.setUserDefinedLabel('<?php print $hostname; ?>');
    dc.setSiteRestriction('<?php print $hostname; ?>');

    var options = new GsearcherOptions();
    options.setExpandMode(GSearchControl.EXPAND_MODE_OPEN);
    options.setRoot(gres);

    var searchControl = new google.search.SearchControl();
    searchControl.addSearcher(dc, options);

    // Tell the searcher to draw itself and tell it where to attach
    searchControl.draw(gctl);

    // Execute an inital search
    searchControl.execute("<?php print $query; ?>");
  }
}
google.setOnLoadCallback(OnLoad);

//]]>
</script>
<div id='gas'>
<h2>Поиск по сайту</h2>
<div id='<?php print $formctl; ?>'></div>
<div id='<?php print $root; ?>'></div>
</div>
<?php endif; ?>
<?php endif; ?>
