tinyMCE.init({
  mode:"textareas",
  editor_selector:"visualEditor",
  theme:"advanced",
  plugins:"safari,inlinepopups,fullscreen,visualchar",
  theme_advanced_buttons1:"bold,italic,underline,strikethrough,separator,bullist,numlist,separator,link,unlink,separator,image,cleanup,separator,charmap,fullscreen",
  theme_advanced_buttons2:"",
  theme_advanced_buttons3:"",
  language:"en",
  file_browser_callback:"mcms_file_pick"
});
