tinyMCE.init({
  mode:"textareas",
  theme:"advanced",
  plugins:"safari,inlinepopups",
  theme_advanced_buttons1:"bold,italic,underline,strikethrough,separator,bullist,numlist,separator,link,unlink",
  theme_advanced_buttons2:"",
  theme_advanced_buttons3:"",
  language:"ru",
  file_browser_callback:"mcms_file_pick"
});
