#!/bin/sh

MCMS_VERSION=$(grep "define('MCMS_VERSION'" < lib/bootstrap.php | sed -e s'@[^0-9.]*@@g')

if [ -z "$MCMS_VERSION" ]; then
    echo "Unable to find version number in lib/bootstrap.php"
    exit 1
fi

git clean -fd

echo "Preparing Molinos CMS v$MCMS_VERSION"

rm -rf package && mkdir -p package/lib/$MCMS_VERSION
cp -R conf doc themes index.php .htaccess.dist package/
cp -R lib/* package/lib/$MCMS_VERSION/

sed -e "s@__VERSION__@$MCMS_VERSION@g" < package/lib/$MCMS_VERSION/bootstrap.php > package/lib/bootstrap.php
rm package/lib/$MCMS_VERSION/bootstrap.php

(cd package && zip -9rq ../molinos-cms-$MCMS_VERSION.zip .htaccess.dist *)
