#!/bin/sh

DIR=$(dirname $0)

UPDATED=$(git diff --name-only lastrelease-master | grep module.ini | cut -d/ -f3 | xargs echo -n | tr ' ' '|')
STALE=$(git diff --name-only lastrelease-master | grep lib/modules/ | egrep -v "lib/modules/(${UPDATED})/" | cut -d/ -f3 | sort -u | sed -e 's#\(.*\)#lib/modules/\1/module.ini#g')
if [ -n "$STALE" ]; then
  if [ -z "$EDITOR" ]; then
    echo "Edit these files: ${STALE}."
    exit 1
  fi
  $EDITOR $STALE
fi

php -f ${DIR}/rebuild-registry.php
. $DIR/changelogs

MCMS_VERSION=$(php -r 'require "'$DIR'/../lib/modules/core/class.loader.php"; echo MCMS_RELEASE; ')
if [ -z "$MCMS_VERSION" ]; then
    echo "Unable to determine version number."
    exit 1
fi

if [ ! -d $DIR/svn/.svn ]; then
  echo "Please checkout dist/* as $DIR/svn, eg:"
  echo "$ svn checkout http://molinos-cms.googlecode.com/svn/dist/??? $DIR/svn"
  exit 1
fi

if [ ! -f $DIR/svn/modules.ini ]; then
  touch $DIR/svn/modules.ini
  svn add $DIR/svn/modules.ini
fi

git clean -fd

echo "Preparing Molinos CMS v$MCMS_VERSION"
zip -q9r molinos-cms-$MCMS_VERSION.zip \
  .htaccess.dist \
  *.php \
  doc \
  lib/modules/admin \
  lib/modules/attachment \
  lib/modules/auth \
  lib/modules/base \
  lib/modules/install \
  lib/modules/modman \
  lib/modules/nodeapi \
  lib/modules/phtml \
  lib/modules/pdo \
  lib/modules/update \
  themes

echo -n "Preparing modules: "
php -f tools/rebuild-modules.php ${DIR}/svn/${MCMS_VERSION}/modules.ini || exit 1

echo "done, uploading."

for ZIP in tmp/modules/*.zip; do
    if [ -f "$ZIP" ]; then
        NAME=$(basename $ZIP)
        echo "$NAME: uploading."
        googlecode_upload.py -s $NAME -p molinos-cms -l Type-Module,R${MCMS_VERSION} $ZIP
    fi
done

svn ci -m "Semi-automatic release." $DIR/svn
