<form id='todosubmitform' method='post' action='<?php print l('?q=todo.rpc&amp;action=add&amp;destination=CURRENT'); ?>'>
<input type='hidden' name='rel' value='<?php print $rel; ?>' />
<input id='todotext' type='text' name='name' />
<input type='submit' value='добавить' class='submit' />
<div class='hint'>Текст напоминания, например: «Починить javascript на www.molinos.ru — не работает меню»</div>
<?php print show_users($users); ?>
<div class='hint'>Если заметка не для тебя — выбери получателя</div>
</form>
<?php

function show_todo(array $list, $type, $title, $linktpl)
{
  print html::em('h3', array(
    'class' => "cold todolist {$type}". (empty($list[$type]) ? ' empty' : ''),
  ), html::em('span', $title));

  if ('open' == $type)
    print html::em('p', array(
      'class' => 'todolist emptymsg '. $type .' '. (empty($list[$type]) ? '' : 'hide'),
      ), 'Этот список пока пуст.  Вам нужно добавить или изменить задание, тогда здесь что-нибудь появится.');

  print "<table class='todolist {$type}'>";

  if (!empty($list[$type])) {
    foreach ($list[$type] as $task) {
      $link = str_replace('$nid', $task['id'], $linktpl);

      $row = html::em('td', html::em('input', array(
        'type' => 'checkbox',
        'value' => $task['id'],
        )));
      $row .= html::em('td', html::em('span', array(
        'class' => 'delete',
        )));
      $row .= html::em('td', l($link, mcms_plain($task['name'])));

      if (mcms::user()->id == $task['uid']['id'])
        $row .= html::em('td');
      else {
        $re = l($task['uid'], null, array('class' => 'userlink'));
        $row .= html::em('td', $re);
      }

      print html::em('tr', array(
        'id' => $task['id'],
        ), $row);
    }
  }

  print '</table>';
}

function show_users(array $list)
{
  $output = '';

  foreach ($list as $id => $name)
    $output .= html::em('option', array(
      'value' => $id,
      'selected' => ($id == mcms::user()->id) ? 'selected' : '',
      ), $name);

  $html = html::em('select', array(
    'id' => 'todouser',
    'name' => 'user',
    ), $output);

  return html::em('div', array(
    'class' => 'todo-setuser',
    ), $html);
}

$text = 'TODO'. ($relname ? ' &rarr; '. l("/node/{$rel}/", $relname) : '');
show_todo($list, 'open', $text, $linktpl);

show_todo($list, 'closed', 'Выполненные задачки', $linktpl);
