<form id='todosubmitform' method='post' action='<?php print l('todo.rpc?action=add&destination=CURRENT'); ?>'>
<input type='hidden' name='rel' value='<?php print $rel; ?>' />
<input id='todotext' type='text' name='name' />
<input type='submit' value='добавить' class='submit' />
<div class='hint'>Текст напоминания, например: «Починить javascript на www.molinos.ru — не работает меню»</div>
<?php print show_users($users); ?>
<div class='hint'>Если заметка не для тебя — выбери получателя</div>
</form>
<?php

function show_todo(array $list, $type, $title)
{
  print mcms::html('h3', array(
    'class' => "cold todolist {$type}". (empty($list[$type]) ? ' empty' : ''),
  ), mcms::html('span', $title));

  if ('open' == $type)
    print mcms::html('p', array(
      'class' => 'todolist emptymsg '. $type .' '. (empty($list[$type]) ? '' : 'hide'),
      ), 'Этот список пока пуст.  Вам нужно добавить или изменить задание, тогда здесь что-нибудь появится.');

  print "<div class='todolist {$type}'>";

  if (!empty($list[$type])) {
    foreach ($list[$type] as $task)
      print $task['__html'];
  }

  print '</div>';
}

function show_users(array $list)
{
  $output = '';

  foreach ($list as $id => $name)
    $output .= mcms::html('option', array(
      'value' => $id,
      'selected' => ($id == mcms::user()->id) ? 'selected' : '',
      ), $name);

  $html = mcms::html('select', array(
    'id' => 'todouser',
    'name' => 'user',
    ), $output);

  return mcms::html('div', array(
    'class' => 'todo-setuser',
    ), $html);
}

show_todo($list, 'open', 'TODO'. ($relname ? ' &rarr; '. l("/node/{$rel}/", $relname) : ''));

show_todo($list, 'closed', 'Выполненные задачки'); ?>
